# Generated by Django 4.1.5 on 2023-02-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_user_watchlist_remove_watchlist_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('listing', 'bid_amount')},
        ),
    ]
