# Generated by Django 4.1.5 on 2023-02-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_current_bid_bid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
    ]
